services:
  web:
    container_name: wavecare-web

    build: .

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      NEXT_PUBLIC_API_URL: http://host.docker.internal:3002

    restart: unless-stopped